---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-billing-settlement-db
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "databases/billingsettlementsystem/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-billing-settlement-db-upgrades
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "databases/billingsettlementsystem/upgrades/*").AsConfig | indent 2 }}
