---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-bi-aggregator-db
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "databases/biaggregator/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-bi-aggregator-db-upgrades
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "databases/biaggregator/upgrades/*").AsConfig | indent 2 }}
