---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-imsbridge-db
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "databases/imsbridge/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-imsbridge-db-upgrades
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "databases/imsbridge/upgrades/*").AsConfig | indent 2 }}
