---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-template-management-system-db
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "databases/template_management/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-template-management-system-db-upgrades
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "databases/template_management/upgrades/*").AsConfig | indent 2 }}
