---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-account-management-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-account-management-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/account-management-service"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-account-management-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-account-management-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-management
  namespace: {{ .Release.Namespace }}
  labels:
    app: account-management
spec:
  replicas: {{ .Values.replica.accountmanagement }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 10%
  selector:
    matchLabels:
      app: account-management
  template:
    metadata:
      labels:
        app: account-management
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - account-management
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-account-management-main
          mountPath: /account-management-main
        - name: vol-cm-account-management-templates
          mountPath: /account-management-templates
        - name: vol-cm-account-management-audit-templates
          mountPath: /account-management-audit-templates
        - name: vol-cm-account-management-copy
          mountPath: /scripts
      containers:
      - name: account-management
        image: {{ .Values.image.accountmanagement }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 8092
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8092
          initialDelaySeconds: 30
          periodSeconds: 20
        ports:
        - containerPort: 8092
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-account-management
          mountPath: {{ .Values.logs }}/account-management-service
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-account-management-main
        configMap:
          name: cm-account-management-main
      - name: vol-cm-account-management-templates
        configMap:
          name: cm-account-management-templates
      - name: vol-cm-account-management-audit-templates
        configMap:
          name: cm-account-management-audit-templates
      - name: vol-logs-account-management
        persistentVolumeClaim:
          claimName: logs-account-management-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-account-management-copy
        configMap:
          name: cm-account-management-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-management
  name: svc-account-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8092
    targetPort: 8092
  selector:
    app: account-management
  type: ClusterIP
