---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-bi-engine-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-bi-engine-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/bi-engine"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-bi-engine-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-bi-engine-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bi-report-dir-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
    name: bi-report-dir-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/share/nginx/html/analytics/file"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bi-report-dir-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: bi-report-dir-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-engine
  namespace: {{ .Release.Namespace }}
  labels:
    app: bi-engine
spec:
  replicas: {{ .Values.replica.biengine }}
  selector:
    matchLabels:
      app: bi-engine
  template:
    metadata:
      labels:
        app: bi-engine
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - bi-engine
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-biengine-main
          mountPath: /bi-engine-main
        - name: vol-cm-biengine-templates
          mountPath: /bi-engine-templates
        - name: vol-cm-biengine-scripts
          mountPath: /bi-engine-scripts
        - name: vol-cm-biengine-copy
          mountPath: /scripts
      containers:
      - name: bi-engine
        image: {{ .Values.image.biengine }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8917
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: 500m
            memory: 900Mi
          requests:
            cpu: 200m
            memory: 300Mi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-bi-report-dir
          mountPath: /usr/share/nginx/html/analytics/file
        - name: vol-logs-bi-engine
          mountPath: {{ .Values.logs }}/bi-engine
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-biengine-main
        configMap:
          name: cm-biengine-main
      - name: vol-cm-biengine-templates
        configMap:
          name: cm-biengine-templates
      - name: vol-cm-biengine-scripts
        configMap:
          name: cm-biengine-scripts
      - name: vol-logs-bi-engine
        persistentVolumeClaim:
          claimName: logs-bi-engine-{{ .Release.Namespace }}
      - name: vol-bi-report-dir
        persistentVolumeClaim:
          claimName: bi-report-dir-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-biengine-copy
        configMap:
          name: cm-biengine-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bi-engine
  name: svc-bi-engine
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8917
    targetPort: 8917
  selector:
    app: bi-engine
  type: ClusterIP
