apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-bi-tdr-exporter-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-bi-tdr-exporter-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/bi-tdr-exporter"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-bi-tdr-exporter-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-bi-tdr-exporter-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-tdr-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: bi-tdr-exporter
spec:
  replicas: {{ .Values.replica.bitdrexporter }}
  selector:
    matchLabels:
      app: bi-tdr-exporter
  template:
    metadata:
      labels:
        app: bi-tdr-exporter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - bi-tdr-exporter
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-bi-tdr-exporter-main
          mountPath: /bi-tdr-exporter-main
        - name: vol-cm-bi-tdr-exporter-copy
          mountPath: /scripts
      containers:
      - name: accountlink
        image: {{ .Values.image.bitdrexporter }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8091
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-bi-tdr-exporter
          mountPath: {{ .Values.logs }}/bi-tdr-exporter
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-bi-tdr-exporter-main
        configMap:
          name: cm-bi-tdr-exporter-main
      - name: vol-logs-bi-tdr-exporter
        persistentVolumeClaim:
          claimName: logs-bi-tdr-exporter-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-bi-tdr-exporter-copy
        configMap:
          name: cm-bi-tdr-exporter-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: accountlink
  name: svc-accountlink
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8091
    targetPort: 8091
  selector:
    app: accountlink
  type: ClusterIP
