---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-billing-settlement-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-billing-settlement-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/billing-settlement"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-billing-settlement-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-billing-settlement-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-settlement-system
  namespace: {{ .Release.Namespace }}
  labels:
    app: billing-settlement-system
spec:
  replicas: {{ .Values.replica.billingsettlement }}
  selector:
    matchLabels:
      app: billing-settlement-system
  template:
    metadata:
      labels:
        app: billing-settlement-system
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - billing-settlement-system
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-billing-settlement-main
          mountPath: /billing-settlement-main
        - name: vol-cm-billing-settlement-feeder
          mountPath: /billing-settlement-feeder
        - name: vol-cm-billing-settlement-copy
          mountPath: /scripts
      containers:
      - name: billing-settlement
        image: {{ .Values.image.billingsettlement }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-billing-settlement
          mountPath: {{ .Values.logs }}/billing-settlement
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-billing-settlement-main
        configMap:
          name: cm-billing-settlement-main
      - name: vol-cm-billing-settlement-feeder
        configMap:
          name: cm-billing-settlement-feeder
      - name: vol-logs-billing-settlement
        persistentVolumeClaim:
          claimName: logs-billing-settlement-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-billing-settlement-copy
        configMap:
          name: cm-billing-settlement-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: billing-settlement
  name: svc-billing-settlement
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: billing-settlement
  type: ClusterIP
