apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-cell-sim-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-cell-sim-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/cell-sim"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cell-sim-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-cell-sim-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-sim
  namespace: {{ .Release.Namespace }}
  labels:
    app: cell-sim
spec:
  replicas: {{ .Values.replica.cellsim }}
  selector:
    matchLabels:
      app: cell-sim
  template:
    metadata:
      labels:
        app: cell-sim
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cell-sim
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-cell-sim-main
          mountPath: /cell-sim
        - name: vol-cm-cell-sim-copy
          mountPath: /scripts
      containers:
      - name: cell-sim
        image: {{ .Values.image.cellsim }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9907
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-cell-sim
          mountPath: {{ .Values.logs }}/accountlinksimulator
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-cell-sim-main
        configMap:
          name: cm-cell-sim-main
      - name: vol-logs-cell-sim
        persistentVolumeClaim:
          claimName: logs-cell-sim-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-cell-sim-copy
        configMap:
          name: cm-cell-sim-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cell-sim
  name: svc-cell-sim
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 9907
    targetPort: 9907
  selector:
    app: cell-sim
  type: ClusterIP
