---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-group-management-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-group-management-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/group-management"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-group-management-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-group-management-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-management
  namespace: {{ .Release.Namespace }}
  labels:
    app: group-management
spec:
  replicas: {{ .Values.replica.groupmanagement }}
  selector:
    matchLabels:
      app: group-management
  template:
    metadata:
      labels:
        app: group-management
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - group-management
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
          - name: config-dir-main
            mountPath: {{ .Values.conf }}
          - name: vol-cm-main
            mountPath: /main
          - name: vol-cm-group-management-main
            mountPath: /group-management-main
          - name: vol-cm-group-management-audit
            mountPath: /group-management-audit
          - name: vol-cm-group-management-notification
            mountPath: /group-management-notification
          - name: vol-cm-group-management-tdr
            mountPath: /group-management-tdr
          - name: vol-cm-group-management-copy
            mountPath: /scripts
      containers:
      - name: group-management
        image: {{ .Values.image.groupmanagement }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-group-management
          mountPath: {{ .Values.logs }}/group-management
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-group-management-main
        configMap:
          name: cm-group-management-main
      - name: vol-cm-group-management-audit
        configMap:
          name: cm-group-management-audit
      - name: vol-cm-group-management-notification
        configMap:
          name: cm-group-management-notification
      - name: vol-cm-group-management-tdr
        configMap:
          name: cm-group-management-tdr
      - name: vol-logs-group-management
        persistentVolumeClaim:
          claimName: logs-group-management-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-group-management-copy
        configMap:
          name: cm-group-management-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: group-management
  name: svc-group-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8084
    targetPort: 8084
  selector:
    app: group-management
  type: ClusterIP
