---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-ims-bridge-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-ims-bridge-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/ims-bridge"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-ims-bridge-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-ims-bridge-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-bridge
  namespace: {{ .Release.Namespace }}
  labels:
    app: ims-bridge
spec:
  replicas: {{ .Values.replica.imsbridge }}
  selector:
    matchLabels:
      app: ims-bridge
  template:
    metadata:
      labels:
        app: ims-bridge
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ims-bridge
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-ims-bridge-main
          mountPath: /ims-bridge
        - name: vol-cm-ims-bridge-copy
          mountPath: /scripts
      containers:
      - name: liveness
        image: yauritux/busybox-curl
        command: ['tail','-f','/dev/null']
        livenessProbe:
          exec:
            command:
            - telnet
            - 127.0.0.1
            - "8919"
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: ims-bridge
        image: {{ .Values.image.imsbridge }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 8919
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8919
          initialDelaySeconds: 60
          periodSeconds: 20
        ports:
        - containerPort: 8919
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        {{- if eq .Values.telemetry_client true }}
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.telemetry_jar }} -Dotel.service.name=ims-bridge -Dotel.traces.exporter=zipkin -Dotel.exporter.zipkin.endpoint=http://{{ .Values.telemetry_server }}:9411/api/v2/spans -Dotel.logs.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.exporter.otlp.endpoint=http://{{ .Values.telemetry_server }}:4318 -Dotel.javaagent.debug=true -Xmx256m"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-ims-bridge
          mountPath: {{ .Values.logs }}/ims-bridge
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-ims-bridge-main
        configMap:
          name: cm-ims-bridge-main
      - name: vol-logs-ims-bridge
        persistentVolumeClaim:
          claimName: logs-ims-bridge-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-ims-bridge-copy
        configMap:
          name: cm-ims-bridge-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Release.Namespace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ims-bridge
  name: svc-ims-bridge
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8919
    targetPort: 8919
  selector:
    app: ims-bridge
  type: ClusterIP
