---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-kyc-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-kyc-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/kyc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-kyc-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-kyc-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc
  namespace: {{ .Release.Namespace }}
  labels:
    app: kyc
spec:
  replicas: {{ .Values.replica.kyc }}
  selector:
    matchLabels:
      app: kyc
  template:
    metadata:
      labels:
        app: kyc
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - kyc
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
          - name: config-dir-main
            mountPath: {{ .Values.conf }}
          - name: vol-cm-main
            mountPath: /main
          - name: vol-cm-kyc-main
            mountPath: /kyc-main
          - name: vol-cm-kyc-templates-audit
            mountPath: /kyc-templates-audit
          - name: vol-cm-kyc-templates-tdr
            mountPath: /kyc-templates-tdr
          - name: vol-cm-kyc-actions
            mountPath: /kyc-actions-groovy
          - name: vol-cm-kyc-mappings
            mountPath: /kyc-mappings
          - name: vol-cm-kyc-notification
            mountPath: /kyc-notification
          - name: vol-cm-kyc-copy
            mountPath: /scripts
      containers:
      - name: kyc
        image: {{ .Values.image.kyc }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8297
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-kyc
          mountPath: {{ .Values.logs }}/kyc
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-kyc-main
        configMap:
          name: cm-kyc-main
      - name: vol-cm-kyc-templates-audit
        configMap:
          name: cm-kyc-templates-audit
      - name: vol-cm-kyc-templates-tdr
        configMap:
          name: cm-kyc-templates-tdr
      - name: vol-cm-kyc-actions
        configMap:
          name: cm-kyc-actions
      - name: vol-cm-kyc-mappings
        configMap:
          name: cm-kyc-mappings
      - name: vol-cm-kyc-notification
        configMap:
          name: cm-kyc-notification
      - name: vol-logs-kyc
        persistentVolumeClaim:
          claimName: logs-kyc-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-kyc-copy
        configMap:
          name: cm-kyc-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kyc
  name: svc-kyc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8297
    targetPort: 8297
  selector:
    app: kyc
  type: ClusterIP
