apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-object-store-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-object-store-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/object-store-manager"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-object-store-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-object-store-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-store
  namespace: {{ .Release.Namespace }}
  labels:
    app: object-store
spec:
  replicas: {{ .Values.replica.objectstore }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: object-store
  template:
    metadata:
      labels:
        app: object-store
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - object-store
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-object-store-main
          mountPath: /object-store-main
        - name: vol-cm-object-store-locales
          mountPath: /object-store-locales
        - name: vol-cm-object-store-copy
          mountPath: /scripts
      containers:
      - name: object-store
        image: {{ .Values.image.objectstore }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 20
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        {{- if eq .Values.telemetry_client true }}
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms500M -Xmx2000M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=1"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 500Mi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-object-store
          mountPath: {{ .Values.logs }}/object-store-manager
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-object-store-main
        configMap:
          name: cm-object-store-main
      - name: vol-cm-object-store-locales
        configMap:
          name: cm-object-store-locales
      - name: vol-logs-object-store
        persistentVolumeClaim:
          claimName: logs-object-store-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-object-store-copy
        configMap:
          name: cm-object-store-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
          persistentVolumeClaim:
            claimName: logs-apmjar-{{ .Release.Namespace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: object-store
  name: svc-object-store
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: object-store
  type: ClusterIP
