---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-otp-management-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-otp-management-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/otp-management-system"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-otp-management-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-otp-management-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-management
  namespace: {{ .Release.Namespace }}
  labels:
    app: otp-management
spec:
  replicas: {{ .Values.replica.otpmanagement }}
  selector:
    matchLabels:
      app: otp-management
  template:
    metadata:
      labels:
        app: otp-management
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - otp-management
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-otp-management-main
          mountPath: /otp-management
        - name: vol-cm-otp-management-copy
          mountPath: /scripts
      containers:
      - name: otp-management
        image: {{ .Values.image.otpmanagement }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8899
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
          - name: tz-{{ .Values.country }}
            mountPath: /etc/localtime
          - name: config-dir-main
            mountPath: {{ .Values.conf }}
          - name: vol-logs-otp-management
            mountPath: {{ .Values.logs }}/otp-management-system
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-otp-management-main
        configMap:
          name: cm-otp-management-main
      - name: vol-logs-otp-management
        persistentVolumeClaim:
          claimName: logs-otp-management-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-otp-management-copy
        configMap:
          name: cm-otp-management-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: otp-management
  name: svc-otp-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8899
    targetPort: 8899
  selector:
    app: otp-management
  type: ClusterIP
