---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-reference-generator-{{ .Release.Namespace }}
  labels:
    type: local
    name: logs-reference-generator-{{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/reference-generator"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-reference-generator-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-reference-generator-{{ .Release.Namespace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-generator
  namespace: {{ .Release.Namespace }}
  labels:
    app: reference-generator
spec:
  replicas: {{ .Values.replica.referencegenerator }}
  selector:
    matchLabels:
      app: reference-generator
  template:
    metadata:
      labels:
        app: reference-generator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - reference-generator
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: NAMESPACE_LOGS
          value: "{{ .Release.Namespace_logs_enabled }}"
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-reference-generator-main
          mountPath: /accountlink
        - name: vol-cm-reference-generator-copy
          mountPath: /scripts
      containers:
      - name: reference-generator
        image: {{ .Values.image.referencegenerator }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9997
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
          - name: tz-{{ .Values.country }}
            mountPath: /etc/localtime
          - name: config-dir-main
            mountPath: {{ .Values.conf }}
          - name: vol-logs-reference-generator
            mountPath: {{ .Values.logs }}/reference-generator
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-reference-generator-main
        configMap:
          name: cm-reference-generator-main
      - name: vol-logs-reference-generator
        persistentVolumeClaim:
          claimName: logs-reference-generator-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-reference-generator-copy
        configMap:
          name: cm-reference-generator-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reference-generator
  name: svc-reference-generator
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 9997
    targetPort: 9997
  selector:
    app: reference-generator
  type: ClusterIP
