---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-account-management-main
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/account-management-service/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-account-management-templates
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/account-management-service/templates/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-account-management-audit-templates
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/account-management-service/auditFeed/templates/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-account-management-copy
  namespace: {{ .Release.Namespace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-account-management-service" | quote }}
