---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-coreproxy-main
  namespace: {{ .Release.Namespace }}
binaryData:
{{- $files := .Files }}
{{- range tuple "configs/coreproxy/digitalwarehouse.key" }}
  {{ (base .) }}: |-
{{ $files.Get . | b64enc | indent 4 }}
{{- end }}
data:
{{- range $path, $_ := .Files.Glob "configs/coreproxy/*" }}
{{- if and (not (hasSuffix ".key" $path)) }}
  {{ regexReplaceAll "(.*)/" $path "" }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-coreproxy-copy
  namespace: {{ .Release.Namespace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-coreproxy" | quote }}
