---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-identity-management-main
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/identity-management/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-identity-management-templates
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/identity-management/templates/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-identity-management-copy
  namespace: {{ .Release.Namespace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-identity-management" | quote }}
