---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-logstash-main
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/logstash/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-logstash-mapping
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/logstash/mapping/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-logstash-ruby
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/logstash/ruby/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-logstash-copy
  namespace: {{ .Release.Namespace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-logstash" | quote }}
