---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-notification-manager-main
  namespace: {{ .Release.Namespace }}
binaryData:
{{- $files := .Files }}
{{- range tuple "configs/notification-manager/SourceSansPro-Regular.ttf" "configs/notification-manager/taraji.jpeg" "configs/notification-manager/tt.jpeg" }}
  {{ (base .) }}: |-
{{ $files.Get . | b64enc | indent 4 }}
{{- end }}
data:
{{- range $path, $_ := .Files.Glob "configs/notification-manager/*" }}
{{- if and (not (hasSuffix ".ttf" $path)) (not (hasSuffix ".jpeg" $path)) }}
  {{ regexReplaceAll "(.*)/" $path "" }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-notification-manager-feeder
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/notification-manager/datafeeder/templates/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-notification-manager-keys
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/notification-manager/keys/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-notification-manager-copy
  namespace: {{ .Release.Namespace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-notification-manager" | quote }}
