#!/bin/bash

## COPY SCHEMA INSTALLER SCRIPT & SETTINGS
cp -L /data/db-ini/* /schema-install/
cp -L /data/db-script/* /schema-install/

mkdir /schema-install/databases

## COPY SCHEMAS SQL
#1 ACCESS MANAGEMENT
cp -rL /data/access_management /schema-install/databases/
mkdir -p /schema-install/databases/access_management/upgrades
cp -rL /data/access_management-upgrade/* /schema-install/databases/access_management/upgrades/

#2 ACCOUNT MANAGEMENT
cp -rL /data/accountmanagement /schema-install/databases/
mkdir -p /schema-install/databases/accountmanagement/upgrades
cp -rL /data/accountmanagement-upgrade/* /schema-install/databases/accountmanagement/upgrades/

#3 AGENT ASSIGNMENT
cp -rL /data/agentassignmentsystem /schema-install/databases/
mkdir -p /schema-install/databases/agentassignmentsystem/upgrades
cp -rL /data/agentassignmentsystem-upgrade/* /schema-install/databases/agentassignmentsystem/upgrades/

#4 ALERTAPP
cp -rL /data/alertapp /schema-install/databases/
mkdir -p /schema-install/databases/alertapp/upgrades
cp -rL /data/alertapp-upgrade/* /schema-install/databases/alertapp/upgrades/

#5 BATCH SCHEDULING
cp -rL /data/batchschedulingsystem /schema-install/databases/
mkdir -p /schema-install/databases/batchschedulingsystem/upgrades
cp -rL /data/batchschedulingsystem-upgrade/* /schema-install/databases/batchschedulingsystem/upgrades/

#6 BI AGGREGATOR
cp -rL /data/biaggregator /schema-install/databases/
mkdir -p /schema-install/databases/biaggregator/upgrades
cp -rL /data/biaggregator-upgrade/* /schema-install/databases/biaggregator/upgrades/

#7 BI TDR EXPORTER
cp -rL /data/bitdrexporter /schema-install/databases/
mkdir -p /schema-install/databases/bitdrexporter/upgrades
cp -rL /data/bitdrexporter-upgrade/* /schema-install/databases/bitdrexporter/upgrades/

#8 BILLING SETTLEMENT
cp -rL /data/billingsettlementsystem /schema-install/databases/
mkdir -p /schema-install/databases/billingsettlementsystem/upgrades
cp -rL /data/billingsettlementsystem-upgrade/* /schema-install/databases/billingsettlementsystem/upgrades/

#9 CONFIG SERVICES
cp -rL /data/config_services /schema-install/databases/
mkdir -p /schema-install/databases/config_services/upgrades
cp -rL /data/config_services-upgrade/* /schema-install/databases/config_services/upgrades/

#10 CONTRACT MANAGEMENT
cp -rL /data/contractmanagement /schema-install/databases/
mkdir -p /schema-install/databases/contractmanagement/upgrades
cp -rL /data/contractmanagement-upgrade/* /schema-install/databases/contractmanagement/upgrades/

#11 GROUP MANAGEMENT
cp -rL /data/groupmanagementsystem /schema-install/databases/
mkdir -p /schema-install/databases/groupmanagementsystem/upgrades
cp -rL /data/groupmanagementsystem-upgrade/* /schema-install/databases/groupmanagementsystem/upgrades/

#12 IMS BRIDGE
cp -rL /data/imsbridge /schema-install/databases/
mkdir -p /schema-install/databases/imsbridge/upgrades
cp -rL /data/imsbridge-upgrade/* /schema-install/databases/imsbridge/upgrades/

#13 INTEGRATION SERVICES
cp -rL /data/integration_services /schema-install/databases/
mkdir -p /schema-install/databases/integration_services/upgrades
cp -rL /data/integration_services-upgrade/* /schema-install/databases/integration_services/upgrades/

#13 INTVENTORY MANAGEMENT
cp -rL /data/inventory_management_system /schema-install/databases/
mkdir -p /schema-install/databases/inventory_management_system/upgrades
cp -rL /data/inventory_management_system-upgrade/* /schema-install/databases/inventory_management_system/upgrades/

#14 KYC
cp -rL /data/kyc /schema-install/databases/
mkdir -p /schema-install/databases/kyc/upgrades
cp -rL /data/kyc-upgrade/* /schema-install/databases/kyc/upgrades/

#15 NOTIFICATION UI
cp -rL /data/notificationui /schema-install/databases/
mkdir -p /schema-install/databases/notificationui/upgrades
cp -rL /data/notificationui-upgrade/* /schema-install/databases/notificationui/upgrades/

#16 OBJECT STORE
cp -rL /data/object_store_manager /schema-install/databases/
mkdir -p /schema-install/databases/object_store_manager/upgrades
cp -rL /data/object_store_manager-upgrade/* /schema-install/databases/object_store_manager/upgrades/

#17 ORDER MANAGEMENT
cp -rL /data/order_management_system /schema-install/databases/
mkdir -p /schema-install/databases/order_management_system/upgrades
cp -rL /data/order_management_system-upgrade/* /schema-install/databases/order_management_system/upgrades/

#18 PRODUCT MANAGEMENT
cp -rL /data/pms /schema-install/databases/
mkdir -p /schema-install/databases/pms/upgrades
cp -rL /data/pms-upgrade/* /schema-install/databases/pms/upgrades/

#19 REGION MANAGEMENT
cp -rL /data/regionmanagement /schema-install/databases/
mkdir -p /schema-install/databases/regionmanagement/upgrades
cp -rL /data/regionmanagement-upgrade/* /schema-install/databases/regionmanagement/upgrades/

#20 REGION MANAGEMENT
cp -rL /data/regionmanagement /schema-install/databases/
mkdir -p /schema-install/databases/regionmanagement/upgrades
cp -rL /data/regionmanagement-upgrade/* /schema-install/databases/regionmanagement/upgrades/

#21 SCC COMMISSION ENGINE
cp -rL /data/scccommission /schema-install/databases/
mkdir -p /schema-install/databases/scccommission/upgrades
cp -rL /data/scccommission-upgrade/* /schema-install/databases/scccommission/upgrades/

#22 SCC DATA AGGREGATOR
cp -rL /data/sccdataaggregator /schema-install/databases/
mkdir -p /schema-install/databases/sccdataaggregator/upgrades
cp -rL /data/sccdataaggregator-upgrade/* /schema-install/databases/sccdataaggregator/upgrades/

#23 SCC ENGINE CORE
cp -rL /data/sccengine /schema-install/databases/
mkdir -p /schema-install/databases/sccengine/upgrades
cp -rL /data/sccengine-upgrade/* /schema-install/databases/sccengine/upgrades/

#24 SCC LIVE DATA INGESTOR
cp -rL /data/scclivedataingestor /schema-install/databases/
mkdir -p /schema-install/databases/scclivedataingestor/upgrades
cp -rL /data/scclivedataingestor-upgrade/* /schema-install/databases/scclivedataingestor/upgrades/

#25 SCC PAYOUT ENGINE
cp -rL /data/sccpayoutengine /schema-install/databases/
mkdir -p /schema-install/databases/sccpayoutengine/upgrades
cp -rL /data/sccpayoutengine-upgrade/* /schema-install/databases/sccpayoutengine/upgrades/

#26 SUBSCRIBER SYSTEM
cp -rL /data/subscribersystem /schema-install/databases/
mkdir -p /schema-install/databases/subscribersystem/upgrades
cp -rL /data/subscribersystem-upgrade/* /schema-install/databases/subscribersystem/upgrades/

#27 TEMPLATE MANAGEMENT
cp -rL /data/template_management /schema-install/databases/
mkdir -p /schema-install/databases/template_management/upgrades
cp -rL /data/template_management-upgrade/* /schema-install/databases/template_management/upgrades/

#28 TRIP MANAGEMENT
cp -rL /data/tripmanagementsystem /schema-install/databases/
mkdir -p /schema-install/databases/tripmanagementsystem/upgrades
cp -rL /data/tripmanagementsystem-upgrade/* /schema-install/databases/tripmanagementsystem/upgrades/

### PENDING
#29 DEALER MANAGEMENT
# cp -rL /data/tripmanagementsystem /schema-install/databases/
# mkdir -p /schema-install/databases/tripmanagementsystem/upgrades
# cp -rL /data/tripmanagementsystem-upgrade/* /schema-install/databases/tripmanagementsystem/upgrades/

#34 TXE
# TRANSACTIONLOG
# TRANSACTION EXPORTER
# DUPLICATE TRANSACTION CHECKER
# BUSINESS COUNTER
# LICENSE COUNTER
# cp -rL /data/tripmanagementsystem /schema-install/databases/
# mkdir -p /schema-install/databases/tripmanagementsystem/upgrades
# cp -rL /data/tripmanagementsystem-upgrade/* /schema-install/databases/tripmanagementsystem/upgrades/

# tail -f /dev/null
