#!/bin/sh

mkdir -p /etc/nginx/conf.d/services
mkdir -p /etc/nginx/conf.d/support

cp -L /nginx-main/nginx.conf /etc/nginx/nginx.conf
cp -L /nginx-confd/default.conf /etc/nginx/conf.d/default.conf
cp -L /nginx-services/* /etc/nginx/conf.d/services/
cp -L /nginx-support/* /etc/nginx/conf.d/support/

git clone -b base $GIT_REPO_LINK /data
unzip /data/guidata.zip -d /data
cp -r /data/html/* /usr/share/nginx/html/


if [[ "$NAMESPACE_LOGS" == "true" ]]; then
    echo "namespace-based logs will be enabled"
    sed -i "s+/var/seamless/log/nginx+/var/seamless/log/${NAMESPACE}/nginx+g" /etc/nginx/nginx.conf
else
    echo "Nothing Required"
fi
