#!/bin/bash

mkdir -p /opt/seamless/conf/template-management-system

cp -L /main/* /opt/seamless/conf/
cp -L /template-management-main/* /opt/seamless/conf/template-management-system/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
  echo "namespace-based logs will be enabled"
  sed -i "s+/var/seamless/log/template-management-system+/var/seamless/log/${NAMESPACE}/template-management-system+g" /opt/seamless/conf/template-management-system/log4j2.xml
else
  echo "Nothing Required"
fi
