#!/bin/bash

mkdir -p /opt/seamless/conf/dealer-management-system/templates/dataFeed

cp -L /main/* /opt/seamless/conf/
cp -L /dealer-management-main/* /opt/seamless/conf/dealer-management-system/
cp -L /dealer-management-templates/* /opt/seamless/conf/dealer-management-system/templates/dataFeed/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
    echo "namespace-based logs will be enabled"
    sed -i "s+/var/seamless/log/dealer-management-system+/var/seamless/log/${NAMESPACE}/dealer-management-system+g" /opt/seamless/conf/dealer-management-system/log4j2.xml
    sed -i "s+/var/seamless/log/dealer-management-system+/var/seamless/log/${NAMESPACE}/dealer-management-system+g" /opt/seamless/conf/dealer-management-system/dealer-management-system.properties
else
    echo "Nothing Required"
fi
