#!/bin/bash

mkdir -p /opt/seamless/conf/businesslogic

cp -L /main/* /opt/seamless/conf/
cp -L /businesslogic/* /opt/seamless/conf/businesslogic/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
    echo "namespace-based logs will be enabled"
    sed -i "s+/var/seamless/log/businesslogic+/var/seamless/log/${NAMESPACE}/businesslogic+g" /opt/seamless/conf/businesslogic/log4j2.xml
else
    echo "Nothing Required"
fi
