#!/bin/bash

mkdir -p /opt/seamless/conf/otp-management-system/

cp -L /main/* /opt/seamless/conf/
cp -L /otp-management/* /opt/seamless/conf/otp-management-system/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
  echo "namespace-based logs will be enabled"
  sed -i "s+/var/seamless/log/otp-management-system+/var/seamless/log/${NAMESPACE}/otp-management-system+g" /opt/seamless/conf/otp-management-system/log4j2.properties
else
    echo "Nothing Required"
fi
