#!/bin/bash

mkdir -p /opt/seamless/conf/account-management-service/templates
mkdir -p /opt/seamless/conf/account-management-service/auditFeed/templates

cp -L /main/* /opt/seamless/conf/
cp -L /account-management-main/* /opt/seamless/conf/account-management-service/
cp -L /account-management-templates/* /opt/seamless/conf/account-management-service/templates/
cp -L /account-management-audit-templates/* /opt/seamless/conf/account-management-service/auditFeed/templates/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
    echo "namespace-based logs will be enabled"
    sed -i "s+/var/seamless/log/account-management-service+/var/seamless/log/${NAMESPACE}/account-management-service+g" /opt/seamless/conf/account-management-service/log4j2.properties
else
    echo "Nothing Required"
fi
