#!/bin/bash

mkdir -p /opt/seamless/conf/accountlinksimulator

cp -L /main/* /opt/seamless/conf/
cp -L /accountlink/* /opt/seamless/conf/accountlinksimulator/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
    echo "namespace-based logs will be enabled"
    sed -i "s+/var/seamless/log/accountlinksimulator+/var/seamless/log/${NAMESPACE}/accountlinksimulator+g" /opt/seamless/conf/accountlinksimulator/log4j.properties
else
    echo "Nothing Required"
fi
