#!/bin/bash

mkdir -p /opt/seamless/conf/bi-engine/{templates,scripts}

cp -L /main/* /opt/seamless/conf/
cp -L /bi-engine-main/* /opt/seamless/conf/bi-engine/
cp -L /bi-engine-templates/* /opt/seamless/conf/bi-engine/templates/
cp -L /bi-engine-scripts/* /opt/seamless/conf/bi-engine/scripts/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
    echo "namespace-based logs will be enabled"
    sed -i "s+/var/seamless/log/bi-engine+/var/seamless/log/${NAMESPACE}/bi-engine+g" /opt/seamless/conf/bi-engine/log4j2.xml
else
    echo "Nothing Required"
fi
