#!/bin/bash

mkdir -p /opt/seamless/conf/group-management/templates/{audit,notification,tdr}

cp -L /main/* /opt/seamless/conf/
cp -L /group-management-main/* /opt/seamless/conf/group-management/
cp -L /group-management-audit/* /opt/seamless/conf/group-management/templates/audit/
cp -L /group-management-notification/* /opt/seamless/conf/group-management/templates/notification/
cp -L /group-management-tdr/* /opt/seamless/conf/group-management/templates/tdr/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
    echo "namespace-based logs will be enabled"
    sed -i "s+/var/seamless/log/group-management+/var/seamless/log/${NAMESPACE}/group-management+g" /opt/seamless/conf/group-management/log4j2.xml
else
    echo "Nothing Required"
fi
