#!/bin/bash

mkdir -p /opt/seamless/conf/bi-tdr-exporter

cp -L /main/* /opt/seamless/conf/
cp -L /bi-tdr-exporter-main/* /opt/seamless/conf/bi-tdr-exporter/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
    echo "namespace-based logs will be enabled"
    sed -i "s+/var/seamless/log/bi-tdr-exporter+/var/seamless/log/${NAMESPACE}/bi-tdr-exporter+g" /opt/seamless/conf/bi-tdr-exporter/log4j2.xml
else
    echo "Nothing Required"
fi
