#!/bin/bash

mkdir -p /opt/seamless/conf/logstash/mapping
mkdir -p /opt/seamless/conf/logstash/ruby

cp -L /main/* /opt/seamless/conf/
cp -L /logstash-main/* /opt/seamless/conf/logstash/
cp -L /logstash-mapping/* /opt/seamless/conf/logstash/mapping/
cp -L /logstash-ruby/* /opt/seamless/conf/logstash/ruby/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
    echo "namespace-based logs will be enabled"
    sed -i "s+/var/seamless/log/logstash+/var/seamless/log/${NAMESPACE}/logstash+g" /opt/seamless/conf/logstash/log4j2.xml
else
    echo "Nothing Required"
fi
