#!/bin/bash

mkdir -p /opt/seamless/conf/object-store-manager/locales

cp -L /main/* /opt/seamless/conf/
cp -L /object-store-main/* /opt/seamless/conf/object-store-manager/
cp -L /object-store-locales/* /opt/seamless/conf/object-store-main/locales/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
  echo "namespace-based logs will be enabled"
  sed -i "s+/var/seamless/log/object-store-manager+/var/seamless/log/${NAMESPACE}/object-store-manager+g" /opt/seamless/conf/object-store-manager/.env
else
  echo "Nothing Required"
fi
