#!/bin/bash

mkdir -p /opt/seamless/conf/notification-ui

cp -L /main/* /opt/seamless/conf/
cp -L /notification-ui/* /opt/seamless/conf/notification-ui/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
  echo "namespace-based logs will be enabled"
  sed -i "s+/var/seamless/log/notification-ui+/var/seamless/log/${NAMESPACE}/notification-ui+g" /opt/seamless/conf/notification-ui//log4j2-spring.xml
else
    echo "Nothing Required"
fi
