#!/bin/bash

mkdir -p /opt/seamless/conf/coreproxy

cp -L /main/* /opt/seamless/conf/
cp -L /coreproxy/* /opt/seamless/conf/coreproxy/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
  echo "namespace-based logs will be enabled"
  sed -i "s+/var/seamless/log/coreproxy+/var/seamless/log/${NAMESPACE}/coreproxy+g" /opt/seamless/conf/coreproxy/log4j.xml
else
  echo "Nothing Required"
fi
