#!/bin/bash

mkdir -p /opt/seamless/conf/reference-generator

cp -L /main/* /opt/seamless/conf/
cp -L /reference-generator/* /opt/seamless/conf/reference-generator/

if [[ "$NAMESPACE_LOGS" == "true" ]]; then
  echo "namespace-based logs will be enabled"
  sed -i "s+/var/seamless/log/reference-generator+/var/seamless/log/${NAMESPACE}/reference-generator+g" /opt/seamless/conf/reference-generator/log4j2.properties
else
  echo "Nothing Required"
fi
